zgw_smart_home:getPosPhread.c lcd.c main.c process.c state.c touch.c work.c 
	arm-linux-gcc -o  zgw_smart_home -lpthread getPosPhread.c lcd.c main.c process.c state.c touch.c work.c 

clean:
	rm zgw_smart_home